apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-tcs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edu-tcs
  template:
    metadata:
      labels:
        app: edu-tcs
    spec:
      containers:
      - name: container
        image: arun3333/edu-tcs-demo:latest
        ports:
        - containerPort: 8080
